# Generated by Django 5.1.7 on 2025-04-04 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.CharField(db_column='id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=200, null=True)),
                ('profile_pic', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'temple',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'village',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid4, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('image', models.JSONField(blank=True, db_column='image', default=list, null=True)),
                ('video', models.JSONField(blank=True, db_column='video', default=list, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.register')),
                ('temple', models.ForeignKey(blank=True, db_column='temple', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.temple')),
                ('village', models.ForeignKey(blank=True, db_column='village', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.village')),
            ],
            options={
                'db_table': 'chatroom',
                'ordering': ['created_at'],
            },
        ),
    ]
